cd $CODEBUILD_SRC_DIR; composer install --no-interaction --prefer-dist
version: 0.2
phases:
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR; composer install --no-interaction --prefer-dist
artifacts:
  files:
    - '**/*'
